apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: ex-aaoaddress
  namespace: amq-client
spec:
  addressName: simple.amqp.test
  queueName: simple.amqp.test
  routingType: anycast