apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 1
    # https://strimzi.io/docs/operators/in-development/using.html#assembly-configuring-external-listeners-str
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        type: internal
        port: 9093
        tls: false
      - name: external
        type: route
        port: 9094
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '2.7'
    storage:
      type: ephemeral
  zookeeper:
    # needed for quorum I believe
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    #userOperator: {}