apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: fuse-amq-client
metadata:
  annotations:
    description: deployment for Fuse AMQP client app
  name: fuse-amq-client
objects:
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: fuse-amq-client
      name: fuse-amq-client
    spec:
      replicas: 1
      selector:
        app: fuse-amq-client
      template:
        metadata:
          labels:
            app: fuse-amq-client
        spec:
          containers:
            - name: fuse-amq-client
              image: ''
              ports:
                - containerPort: 8778
                  name: jolokia
              readinessProbe:
                httpGet:
                  path: actuator/health
                  port: 8081
                initialDelaySeconds: 10
              livenessProbe:
                httpGet:
                  path: actuator/health
                  port: 8081
                initialDelaySeconds: 180
              volumeMounts:
                - name: application-config
                  mountPath: /deployments/config
          volumes:
            - name: application-config
              configMap:
                name: fuse-amq-client
      triggers:
        - type: ImageChange
          imageChangeParams:
            automatic: false
            containerNames:
              - fuse-amq-client
            from:
              kind: ImageStreamTag
              name: fuse-amq-client:${APPLICATION_IMAGE_TAG}
parameters:
  - name: APPLICATION_IMAGE_TAG
    value: latest
